// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? "https://vkdoknffkhocvzrvkcxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  "MISSING_SUPABASE_ANON_KEY";

if (!import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) {
  console.warn("VITE_SUPABASE_PUBLISHABLE_KEY is missing. Set it in your environment to connect to Supabase.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});